[package]
name = "cli-text-editor"
version = "0.1.0"
authors = ["Soviet Kitsune <sovietkitsune@soviet.solutions>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustbox = "*"